sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
env:
  matrix:
  - OPENMP=1 MPICPP=mpic++ OMP_NUM_THREADS=2
  - OPENMP=1 OMP_NUM_THREADS=4
  - OPENMP=0 MPICPP=mpic++ 
  - OPENMP=0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-numpy python-scipy python-matplotlib
  - sudo apt-get install -y openmpi-bin libopenmpi-dev
script: 
 - export OMPI_CXX=$CXX
 - make executable -j 2 OPENMP=$OPENMP MPICPP=$MPICPP
 - cd tests
 - ./run_tests.sh
