language: cpp
compiler:
  - clang
  - gcc
env:
  global:
  - OMPI_CXX=$CXX
  matrix:
  - OPENMP=1
  - OPENMP=0
  - MPICPP=mpic++
  - MPICPP=
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-numpy python-scipy python-matplotlib
  - sudo apt-get install -y openmpi-bin libopenmpi-dev
script: 
 - make executable -j 4 OPENMP=$OPENMP CPP=$MPICPP
 - export OMP_NUM_THREADS=4
